spring:
  application:
    name: commute-check
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    root: INFO
    org:
      hirbernate:
        SQL: debug
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
jwt:
  token:
    header: Authorization
    issuer: seunggulee
    client-secret: dpsdpdlcldpsdlstktjqltmroqkfxlawlrkrgkwlakfwk
    token-validity-in-milliseconds: 300000